language: ruby
rvm:
  - 1.9.3
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database g5_pricing_and_availability_test;' -U postgres
notifications:
  campfire:
    rooms:
      secure: aI6dyzNBa2lolmisnfJzW3tQn+6p3Fa6OT1Tf2SCI7pF5cgFot8Q2fh6rKWOZBPbjIs1iaJsAc8qcnajJkntuqQAk0NdgStzNvECjEdCDmmrwfBsVLbh58GosuQxCsiTDQs56oWTClQbYP025V2wr5U9qXy9KU9gKK5lS4tGMXg=
    template:
          - "%{repository}#%{build_number} %{message} (%{branch} - %{commit} : %{author}) Change view : %{compare_url} Build details : %{build_url}"
    on_success: change
    on_failure: always
